version: '3.8'

services:
    backend:
        build:
            context: ./backend
        ports:
            - '8000:8000'
        volumes:
            - ./backend:/app
        environment:
            - DEBUG=True
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
        depends_on:
            db:
                condition: service_healthy

    frontend:
        build:
            context: ./frontend
        platform: linux/amd64
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/app
        environment:
            - NODE_ENV=development
        stdin_open: true
        tty: true
        command: >
            sh -c "rm -rf node_modules &&
                   npm install &&
                   npm run dev"

    db:
        image: postgres:15
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
